### ISSUE TITLE
Unsure how to get a working Ingress config to hit the API

### ISSUE THREAD

**Issue by mcen1** [ansible/galaxy-operator#108]
**Version**
Please provide the versions of the galaxy-operator and galaxy images in use.
2024.4.3
quay.io/ansible/galaxy-ui@sha256:2dd001f43144e20bf493b720f3a52a445a4787a6a16085be8c687d2f16e38ed0                 
quay.io/ansible/galaxy-ng@sha256:6e49c406f516e78a1f000d4f60abc880b3db094dfcffaa4cc99be7dc442327d3
quay.io/ansible/galaxy-operator@sha256:b4f2ea8960e3ebeb283c226556eb0c0b3cd380374a4df5733113297b6b4efed2                          
**Describe the bug**
I have an ingress.yaml as follows: 
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: galaxy-nginx-ingress
  namespace: galaxy
  annotations:
    app.kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: "nginx"
  rules:
  - host: galaxy.local
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: galaxy-web-svc
              port:
                number: 24880
```
The UI comes up fine, but when I try to go to http://galaxy.local/api/, I'm redirected to http://galaxy.local:8080/api/ (which is invalid since that's an internal pod port in the deployment). I can't seem to figure out a way to successfully route/ingressify this component of Galaxy. I searched around in the documentation https://ansible.readthedocs.io/projects/galaxy-operator/en/latest/ but nothing was jumping out at me. I'm sorry if this is something simple or I missed it.

**To Reproduce**
Create an ingress file as above, access http://galaxy.local/api/, be redirected to http://galaxy.local:8080/api/ which is invalid

**Expected behavior**

I would expect that I'd see http://galaxy.local/api/ with something resembling https://galaxy.ansible.com/api/ or some other swagger API interface.

**Additional context**
Can't think of anything else
