### ISSUE TITLE
Consolidate default pulp-api image setting to common role

### ISSUE THREAD

**Issue by rooftopcellist** [ansible/galaxy-operator#30]
Currently, we run the following tasks in the api, content, and worker roles, all of which use the same image.  We should consolidate this and move it to the `common` role.  

```yaml
- name: Set default pulp-api image
  set_fact:
    _default_image: "{{ _image }}:{{ _image_version }}"

- name: Set user provided pulp-api image
  set_fact:
    _custom_image: "{{ image }}:{{ image_version }}"
  when:
    - image is defined and image != ''
    - image_version is defined and image_version != ''

- name: Set pulp-api image URL
  set_fact:
    _image: "{{ _custom_image | default(lookup('env', 'RELATED_IMAGE_PULP')) | default(_default_image, true) }}"

```
