### ISSUE TITLE
spec.pulp_settings.GALAXY_FEATURE_FLAGS.execution_environments wrong type

### ISSUE THREAD

**Issue by Svenum** [ansible/galaxy-operator#85]
**Describe the bug**
spec.pulp_settings.GALAXY_FEATURE_FLAGS.execution_environments in the CRD galaxy has the wrong type. If I set it to `false` I get the error "value false not known. Did you mean: "False""
So it must be of type string and written like `"True"` or `"False"`.

**To Reproduce**
Deploy:
```yml
---
apiVersion: galaxy.ansible.com/v1beta1
kind: Galaxy
metadata:
  name: galaxy
  namespace: galaxy
spec:
  hostname: galaxy-kube.example.com
  ingress_type: ingress
  storage_type: File
  file_storage_access_mode: ReadWriteOnce
  file_storage_size: 8Gi
  no_log: false
  api:
    replicas: 2
  content:
    replicas: 2
  web:
    replicas: 2
  worker:
    replicas: 2
  postgres_configuration_secret: galaxy-postgres-configuration
  pulp_settings:
    GALAXY_FEATURE_FLAGS:
        execution_environments: false
    GALAXY_ENABLE_UNAUTHENTICATED_COLLECTION_ACCESS: "True"
    GALAXY_ENABLE_UNAUTHENTICATED_COLLECTION_DOWNLOAD: "True"
```

**Expected behavior**
EEs should be disabled.
